### ISSUE TITLE
tool

### ISSUE THREAD

**Issue by jitesh-eng** [KasRoudra/PyPhisher#2]
this tool don't install in my kali linux

**Comment by KasRoudra** [comment]
@jitesh-eng Give a screenshot

**Comment by jitesh-eng** [comment]
──(root💀kali)-[/home/kali/Desktop]
└─# git clone https://github.com/KasRoudra/pyphisher.git                                           128 ⨯
Cloning into 'pyphisher'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (32/32), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 358 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
                                                                                                         
┌──(root💀kali)-[/home/kali/Desktop]
└─#                                                                                                128 ⨯

look this my error

**Comment by KasRoudra** [comment]
@jitesh-eng Looks like the problem is with your terminal. Can you git clone other repository sucessfully? Try 

`git config --global http.postBuffer 1048576000` and 

`apt install gnutls-bin`. 

If the problem remains visit [Stackoverflow](https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutlsl)
